openapi: 3.0.0
info:
  title: App For You API
  version: 1.0.0
  description: API

components:
  schemas:
    Exercise:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        weight_kg:
          type: number
          format: float
        repetitions:
          type: integer
        duration_sec:
          type: integer
        rest:
          type: integer
          default: 90

    ExerciseDay:
      type: object
      required:
        - day
      properties:
        day:
          type: string
        at_home:
          type: boolean
          default: false
        wakeup_time:
          type: string
        available_exercise_time:
          type: integer
          description: Total available time for exercise in minutes
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
