# """
# Auto-generated models from JSON Schema
# DO NOT EDIT THIS FILE MANUALLY
# Run: python models.py to regenerate
# """
# from pydantic import BaseModel
# from typing import Optional, Union, List
# from datetime import datetime


# class Exercise(BaseModel):
#     name: str  # Name of the exercise
#     weight_kg: Optional[float] = None  # Weight in kilograms
#     repetitions: Optional[int] = None  # Number of repetitions
#     duration_sec: Optional[int] = None  # Duration in seconds
#     rest: Optional[int] = 90  # Rest time in seconds

# class RunningDistance(BaseModel):
#     distance_km: float  # Distance in kilometers
#     duration_min: str  # Duration in minutes

# class RunningIntervals(BaseModel):
#     speed_km: float  # Speed in km/h
#     duration_sec: str  # Duration in seconds
#     rest: str  # Rest time
#     repetitions: int  # Number of repetitions

# class ExerciseDay(BaseModel):
#     date: str  # Date in YYYY-MM-DD format
#     wakeup_time: Optional[str]  # Wake up time
#     sleep_quality: Optional[int] = None  # Sleep quality scale from 1 to 10
#     available_exercise_time: Optional[int] = None  # Available exercise time in minutes
#     exercises: Optional[List[Union[Exercise, RunningDistance, RunningIntervals]]] = None
#     at_home: bool = True  # Whether the person is at home