# coding: utf-8

"""
    Workout API

    API for managing workout exercises and routines

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from models.models.exercise import Exercise

class TestExercise(unittest.TestCase):
    """Exercise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Exercise:
        """Test Exercise
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Exercise`
        """
        model = Exercise()
        if include_optional:
            return Exercise(
                name = '',
                weight_kg = 1.337,
                repetitions = 56,
                duration_sec = 56,
                rest = 56
            )
        else:
            return Exercise(
                name = '',
        )
        """

    def testExercise(self):
        """Test Exercise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
