# coding: utf-8

"""
    Workout API

    API for managing workout exercises and routines

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from models.models.exercise_day import ExerciseDay

class TestExerciseDay(unittest.TestCase):
    """ExerciseDay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseDay:
        """Test ExerciseDay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseDay`
        """
        model = ExerciseDay()
        if include_optional:
            return ExerciseDay(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                exercises = [
                    models.models.exercise.Exercise(
                        name = '', 
                        weight_kg = 1.337, 
                        repetitions = 56, 
                        duration_sec = 56, 
                        rest = 56, )
                    ]
            )
        else:
            return ExerciseDay(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                exercises = [
                    models.models.exercise.Exercise(
                        name = '', 
                        weight_kg = 1.337, 
                        repetitions = 56, 
                        duration_sec = 56, 
                        rest = 56, )
                    ],
        )
        """

    def testExerciseDay(self):
        """Test ExerciseDay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
