// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdK8faj02cuSahzFa9lv4IXv_oqaeQ6ZE',
    appId: '1:1050310982145:web:3fb51c3d7cfa500c7c9e00',
    messagingSenderId: '1050310982145',
    projectId: 'final-app-429707',
    authDomain: 'final-app-429707.firebaseapp.com',
    storageBucket: 'final-app-429707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIctV7kkjeQecDRHtRD_4Zr2cil7MMmI',
    appId: '1:1050310982145:android:1262b540a98b0b077c9e00',
    messagingSenderId: '1050310982145',
    projectId: 'final-app-429707',
    storageBucket: 'final-app-429707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2R0h3DcLdAi4F57J75WUcDi3yltoy0o',
    appId: '1:1050310982145:ios:5f2b3865a0bf7e447c9e00',
    messagingSenderId: '1050310982145',
    projectId: 'final-app-429707',
    storageBucket: 'final-app-429707.firebasestorage.app',
    iosClientId: '1050310982145-acqklksuo63jrnnfd2vf2oln3id4jl7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2R0h3DcLdAi4F57J75WUcDi3yltoy0o',
    appId: '1:1050310982145:ios:5f2b3865a0bf7e447c9e00',
    messagingSenderId: '1050310982145',
    projectId: 'final-app-429707',
    storageBucket: 'final-app-429707.firebasestorage.app',
    iosClientId: '1050310982145-acqklksuo63jrnnfd2vf2oln3id4jl7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdK8faj02cuSahzFa9lv4IXv_oqaeQ6ZE',
    appId: '1:1050310982145:web:eccb48f1a08ababf7c9e00',
    messagingSenderId: '1050310982145',
    projectId: 'final-app-429707',
    authDomain: 'final-app-429707.firebaseapp.com',
    storageBucket: 'final-app-429707.firebasestorage.app',
  );

}