name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  REGION: europe-west2
  SERVICE_NAME: life-automation-api

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          cd backend
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }},CLOUD_RUN_URL=${{ secrets.CLOUD_RUN_URL }},ADMIN_EMAILS=${{ secrets.ADMIN_EMAILS }},ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}"

      - name: Update Composer environment variables
        run: |
          gcloud composer environments run aiapps \
            --location ${{ env.REGION }} \
            variables set -- BACKEND_API_URL ${{ secrets.CLOUD_RUN_URL }}

      - name: Upload DAGs to Composer
        run: |
          gcloud composer environments storage dags import \
            --environment aiapps \
            --location ${{ env.REGION }} \
            --source backend/dags/scheduler.dag.py

          gcloud composer environments storage dags import \
            --environment aiapps \
            --location ${{ env.REGION }} \
            --source backend/dags/uniques.dag.py

          gcloud composer environments storage dags import \
            --environment aiapps \
            --location ${{ env.REGION }} \
            --source backend/dags/delete_incomplete.dag.py

      - name: Deployment summary
        run: |
          echo "## Deployment Successful! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Service**: ${{ env.SERVICE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Region**: ${{ env.REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: ${{ secrets.CLOUD_RUN_URL }}" >> $GITHUB_STEP_SUMMARY
